- name: Demo task from role
  debug:
        msg: demo task from role

- name: Install web server
  yum: 
        name: httpd
        state: installed
  notify: Restart HTTPD

- name: copy template
  template:
        src: demo-template.j2
        dest: /tmp/demo-template

