- name: Create Web Layer in Stack
  hosts: DEV
  become: yes
  gather_facts: yes

  tasks:
    - name: Install Web Server
      yum:
        name: "{{item}}"
        state: installed
      with_items:
        - httpd
        - httpd-devel
        - gcc

    - name: Download mod_jk  and extract it
      #get_url: 
      #  url: http://redrockdigimark.com/apachemirror/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.42-src.tar.gz
      #  dest: /root/tomcat-connectors-1.2.42-src.tar.gz
      unarchive:
        src: http://redrockdigimark.com/apachemirror/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.42-src.tar.gz
        dest: /root
        remote_src: yes

    - name: Compile mod_jk
      shell: "{{item}}"
      args:
        chdir: /root/tomcat-connectors-1.2.42-src/native
      with_items:
        - "./configure --with-apxs=/bin/apxs"
        - make 
        - make install

    - name: Create workers.properties file
      blockinfile:
        path: /etc/httpd/conf.d/workers.properties
        create: yes
        block: |
            worker.list=tomcatA
            worker.tomcatA.type=ajp13
            worker.tomcatA.host=localhost
            worker.tomcatA.port=8009

    - name: Create mod_jk.conf file
      blockinfile:
        path: /etc/httpd/conf.d/mod_jk.conf
        create: yes
        block: |
            LoadModule jk_module modules/mod_jk.so
            JkWorkersFile conf.d/workers.properties
            JkLogFile logs/mod_jk.log
            JkLogLevel info
            JkLogStampFormat "[%a %b %d %H:%M:%S %Y]"
            JkOptions +ForwardKeySize +ForwardURICompat -ForwardDirectories
            JkRequestLogFormat "%w %V %T"
            JkMount /student tomcatA
            JkMount /student/* tomcatA

    - name: Restart web Server
      service: 
        name: httpd
        state: restarted